apps/project/urls.py
# Django Library
from django.contrib.auth import views as auth_views
from django.urls import path

# Localfolder Library
from .views.bug import (
    BugCreateView, BugDetailView, BugListView, BugUpdateView, DeleteBug)
from .views.project import (
    DeleteProject, ProjectCreateView, ProjectDetailView, ProjectListView,
    ProjectUpdateView)
from .views.task import (
    DeleteTask, TaskCreateView, TaskDetailView, TaskListView, TaskUpdateView)

app_name = 'project'

urlpatterns = [
    path('task', TaskListView.as_view(), name='task'),
    path('task/add/', TaskCreateView.as_view(), name='task-add'),
    path('task/<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('task/<int:pk>/update', TaskUpdateView.as_view(), name='task-update'),
    path('task/<int:pk>/delete/', DeleteTask, name='task-delete'),

    path('project', ProjectListView.as_view(), name='project'),
    path('project/add/', ProjectCreateView.as_view(), name='project-add'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('project/<int:pk>/update', ProjectUpdateView.as_view(), name='project-update'),
    path('project/<int:pk>/delete/', DeleteProject, name='project-delete'),

    path('bug', BugListView.as_view(), name='bug'),
    path('bug/add/', BugCreateView.as_view(), name='bug-add'),
    path('bug/<int:pk>/', BugDetailView.as_view(), name='bug-detail'),
    path('bug/<int:pk>/update', BugUpdateView.as_view(), name='bug-update'),
    path('bug/<int:pk>/delete/', DeleteBug, name='bug-delete'),
]

apps/webodoobim/urls.py
# Django Library
from django.conf.urls import url
from django.urls import path

# Localfolder Library
from .views.views import about, blog, contact, index, services

app_name = 'webodoobim'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'about/', about, name='about'),
    url(r'services/', services, name='services'),
    url(r'contact/', contact, name='contact'),
    url(r'blog/', blog, name='blog'),

]

pyerp/urls.py
"""Rutas de PyErp
"""
# Django Library
# Librerias Django
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.views.static import serve

# Thirdparty Library
# Librerias de terceros
from apps.base.views import ActivateLanguageView
from pyerp.settings import BASE_DIR

urlpatterns = [
    path('', include('apps.base.home_urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.base.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT, }),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT, }),
    # path('', include('apps.home.urls')),
]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path(
        '<language_code>/language/activate/',
        ActivateLanguageView.as_view(),
        name='activate_language'
    ),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]


# ========================================================================== #
# Recorrer el archivo de aplicaciones instaladas y construir sus rutas
with open('%s/installed_apps.py' % BASE_DIR, 'r') as ins_apps_file:
    for line in ins_apps_file.readlines():
        if line.strip() == 'apps.home':
            urlpatterns.pop(0)
            urlpatterns += [path('', include('apps.home.urls'))]

        elif line.strip() == 'apps.webodoobim':
            urlpatterns.pop(0)
            urlpatterns += [path('', include('apps.webodoobim.urls'))]

        else:
            _, app = line.split('.')
            urlpatterns += [
                path(
                    '{}/'.format(app.rstrip('\n')),
                    include('{}.urls'.format(line.strip()))
                )
            ]

apps/project/models.py
# Localfolder Library
from .submodels.bug import PyBug
from .submodels.project import PyProject
from .submodels.task import PyTask

apps/project/models/bug.py
# Django Library
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

# Thirdparty Library
from apps.base.models import PyFather

BUG_STATE = (
        ("nuevo", "Nuevo"),
        ('trabajando', 'Trabajando'),
        ('finalizado', 'Finalizado')
    )


class PyBug(PyFather):
    name = models.CharField('Nombre', max_length=80)
    note = models.TextField(blank=True, null=True)

    state = models.CharField(
        choices=BUG_STATE, max_length=64, default='nuevo')

    def get_absolute_url(self):
        return reverse('project:bug-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return format(self.name)

apps/project/models/project.py
# Django Library
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

# Thirdparty Library
from apps.base.models import PyFather

PROJECT_STATE = (
        ("nuevo", "Nuevo"),
        ('trabajando', 'Trabajando'),
        ('finalizado', 'Finalizado')
    )


class PyProject(PyFather):
    name = models.CharField('Nombre', max_length=80)
    note = models.TextField(blank=True, null=True)

    state = models.CharField(
        choices=PROJECT_STATE, max_length=64, default='nuevo')

    def get_absolute_url(self):
        return reverse('project:project-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return format(self.name)

apps/project/models/task.py
# Django Library
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

# Thirdparty Library
from apps.base.models import PyFather

# Localfolder Library
from .project import PyProject

TASK_STATE = (
        ("nuevo", "Nuevo"),
        ('trabajando', 'Trabajando'),
        ('finalizado', 'Finalizado')
    )


class PyTask(PyFather):
    name = models.CharField('Nombre', max_length=80)
    note = models.TextField(blank=True, null=True)
    project_id = models.ForeignKey(PyProject, null=True, blank=True, on_delete=models.PROTECT)

    state = models.CharField(
        choices=TASK_STATE, max_length=64, default='nuevo')

    def get_absolute_url(self):
        return reverse('project:task-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return format(self.name)

apps/webodoobim/models.py
# Django Library
from django.db import models

# Create your models here.

apps/base/views/blog.py
# Furture Library
from __future__ import unicode_literals

# Django Library
from django.contrib.auth.mixins import LoginRequiredMixin

# Localfolder Library
from ..models import PyWParameter
from ..models.post import PyPost
from .web_father import FatherDetailView, FatherListView


def _web_parameter():
    web_parameter = {}
    for parametro in PyWParameter.objects.all():
        web_parameter[parametro.name] = parametro.value
    return web_parameter

OBJECT_LIST_FIELDS = [
    {'string': 'Título', 'field': 'title'},
    {'string': 'Creado en', 'field': 'created_on'},
    {'string': 'Contenido', 'field': 'content'},
]

OBJECT_FORM_FIELDS = ['title', 'content', 'created_on']

class BlogView(FatherListView):
    model = PyPost
    template_name = 'blog/blog.html'
    fields = OBJECT_LIST_FIELDS
    paginate_by = 8
    extend_from = None
    url_web_post = None
    header_title = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extend_from'] = self.extend_from
        context['url_web_post'] = self.url_web_post
        context['header_title'] = self.header_title

        return context

class PostDetailView(LoginRequiredMixin, FatherDetailView):
    model = PyPost
    template_name = 'blog/post.html'
    extend_from = None
    url_web_post = None
    header_title = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extend_from'] = self.extend_from
        context['url_web_post'] = self.url_web_post
        context['header_title'] = self.header_title
        return context

apps/project/views/bug.py
# Django Library
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

# Localfolder Library
from ..models.bug import PyBug

""" BEGIN BUG """
BUG_FIELDS = [
            {'string': 'Nombre', 'field': 'name'},
            {'string': 'Estado', 'field': 'state'},
            {'string': 'Notas', 'field': 'note'},
        ]

BUG_FIELDS_SHORT = ['name','state', 'note']


class BugListView(LoginRequiredMixin, ListView):
    model = PyBug
    template_name = 'base/list.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(BugListView, self).get_context_data(**kwargs)
        context['title'] = 'Errores'
        context['detail_url'] = 'project:bug-detail'
        context['add_url'] = 'project:bug-add'
        context['fields'] = BUG_FIELDS
        return context

class BugDetailView(LoginRequiredMixin, DetailView):
    model = PyBug
    template_name = 'base/detail.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(BugDetailView, self).get_context_data(**kwargs)
        context['title'] = context['object'].name
        context['breadcrumbs'] = [{'url': 'project:bug', 'name': 'Error'}]
        context['update_url'] = 'project:bug-update'
        context['delete_url'] = 'project:bug-delete'
        context['fields'] = BUG_FIELDS
        return context

class BugCreateView(LoginRequiredMixin, CreateView):
    model = PyBug
    fields = BUG_FIELDS_SHORT
    template_name = 'base/form.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(BugCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Crear Error'
        context['breadcrumbs'] = [{'url': 'project:bug', 'name': 'Error'}]
        context['back_url'] = reverse('project:bug')
        return context

class BugUpdateView(LoginRequiredMixin, UpdateView):
    model = PyBug
    fields = BUG_FIELDS_SHORT
    template_name = 'base/form.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(BugUpdateView, self).get_context_data(**kwargs)
        context['title'] = context['object'].name
        context['breadcrumbs'] = [{'url': 'project:bug', 'name': 'Error'}]
        context['back_url'] = reverse('base:bug-detail', kwargs={'pk': context['object'].pk})
        return context


@login_required(login_url="base:login")
def DeleteBug(self, pk):
    bug = PyBug.objects.get(id=pk)
    bug.delete()
    return redirect(reverse('project:bug'))

apps/project/views/project.py
# Django Library
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

# Localfolder Library
from ..models.project import PyProject

PROJECT_FIELDS = [
            {'string': 'Nombre', 'field': 'name'},
            {'string': 'Estado', 'field': 'state'},
            {'string': 'Notas', 'field': 'note'},
        ]

PROJECT_FIELDS_SHORT = ['name','state', 'note']


class ProjectListView(LoginRequiredMixin, ListView):
    model = PyProject
    template_name = 'base/list.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context['title'] = 'Proyectos'
        context['detail_url'] = 'project:project-detail'
        context['add_url'] = 'project:project-add'
        context['fields'] = PROJECT_FIELDS
        return context

class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = PyProject
    template_name = 'base/detail.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        context['title'] = context['object'].name
        context['breadcrumbs'] = [{'url': 'project:project', 'name': 'Proyecto'}]
        context['update_url'] = 'project:project-update'
        context['delete_url'] = 'project:project-delete'
        context['fields'] = PROJECT_FIELDS
        return context

class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = PyProject
    fields = PROJECT_FIELDS_SHORT
    template_name = 'base/form.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(ProjectCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Crear Proyecto'
        context['breadcrumbs'] = [{'url': 'project:project', 'name': 'Proyecto'}]
        context['back_url'] = reverse('project:project')
        return context

class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    model = PyProject
    fields = PROJECT_FIELDS_SHORT
    template_name = 'base/form.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(ProjectUpdateView, self).get_context_data(**kwargs)
        context['title'] = context['object'].name
        context['breadcrumbs'] = [{'url': 'project:project', 'name': 'Proyecto'}]
        context['back_url'] = reverse('project:project-detail', kwargs={'pk': context['object'].pk})
        return context


@login_required(login_url="base:login")
def DeleteProject(self, pk):
    project = PyProject.objects.get(id=pk)
    project.delete()
    return redirect(reverse('project:project'))

apps/project/views/task.py
# Django Library
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView

# Localfolder Library
from ..models.task import PyTask

TASK_FIELDS = [
            {'string': 'Nombre', 'field': 'name'},
            {'string': 'Estado', 'field': 'state'},
            {'string': 'Proyecto', 'field': 'project_id'},
            {'string': 'Notas', 'field': 'note'},
        ]

TASK_FIELDS_SHORT = ['name','state','project_id','note']


class TaskListView(LoginRequiredMixin, ListView):
    model = PyTask
    template_name = 'base/list.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        context['title'] = 'Tareas'
        context['detail_url'] = 'project:task-detail'
        context['add_url'] = 'project:task-add'
        context['fields'] = TASK_FIELDS
        return context

class TaskDetailView(LoginRequiredMixin, DetailView):
    model = PyTask
    template_name = 'base/detail.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(TaskDetailView, self).get_context_data(**kwargs)
        context['title'] = context['object'].name
        context['breadcrumbs'] = [{'url': 'project:task', 'name': 'Tarea'}]
        context['update_url'] = 'project:task-update'
        context['delete_url'] = 'project:task-delete'
        context['fields'] = TASK_FIELDS
        return context

class TaskCreateView(LoginRequiredMixin, CreateView):
    model = PyTask
    fields = TASK_FIELDS_SHORT
    template_name = 'base/form.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(TaskCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Crear Tarea'
        context['breadcrumbs'] = [{'url': 'project:task', 'name': 'Tarea'}]
        context['back_url'] = reverse('project:task')
        return context

class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = PyTask
    fields = TASK_FIELDS_SHORT
    template_name = 'base/form.html'
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = super(TaskUpdateView, self).get_context_data(**kwargs)
        context['title'] = context['object'].name
        context['breadcrumbs'] = [{'url': 'project:task', 'name': 'Tarea'}]
        context['back_url'] = reverse('project:task-detail', kwargs={'pk': context['object'].pk})
        return context


@login_required(login_url="base:login")
def DeleteTask(self, pk):
    task = PyTask.objects.get(id=pk)
    task.delete()
    return redirect(reverse('project:task'))

apps/webodoobim/views.py
# Django Library
from django.shortcuts import render

# Create your views here.

apps/webodoobim/views/views.py
# Furture Library
from __future__ import unicode_literals

# Django Library
from django.core.mail import EmailMessage
from django.shortcuts import HttpResponse, render
from django.template.loader import render_to_string
from django.views.generic import DetailView, ListView

BIM_PHONE = "+56 9 4299 4534"

def index(request):
    return render(request, 'webodoobim/index.html')

def about(request):
    return render(request, 'webodoobim/about.html')

def services(request):
    return render(request, 'webodoobim/services.html')

def contact(request):
    return render(request, 'webodoobim/contact_us.html')

def blog(request):
    return render(request, 'webodoobim/blog.html')

apps/webodoobim/templates/webodoobim/header.html
{% load static %}
{% load erp_tags %}
<!DOCTYPE html>
<!--
Template Name: The Billtro
Version: 1.0.0
Author:
Website:
Purchase:
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="zxx">
<!--[endif]-->

<head>
    <meta charset="utf-8" />
    <title>BIM Odoo | {{ user|get_company_name }}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="description" content="smart pest" />
    <meta name="keywords" content="The Billtro /construction/ builder" />
    <meta name="author" content="" />
    <meta name="MobileOptimized" content="320" />
    <!--start theme style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/meanmenu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slicknav.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'venobox/css/venobox.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/camera.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
    <!-- favicon link-->
    <link rel="shortcut icon" type="image/icon" href="{% static 'img/favicon.png' %}">
</head>

<body>
    <!-- preloader Start -->
    <div id="preloader">
        <div id="status">
            <img src="{% static 'images/preloader.gif' %}" id="preloader_image" alt="loader">
        </div>
    </div>
    <a href="javascript:" id="return-to-top"><i class="fa fa-angle-up"></i></a>
    <!-- tb header Start -->
    <header>
        <div class="topbar">
            <div class="container">

                <div class="top_header_add hidden-xs hidden-sm">
                    <ul>
                        <li><i class="fa fa-phone" aria-hidden="true"></i> + 56 9 4299 4534</li>
                        <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i> ventas@ynext.cl</a></li>
                    </ul>
                </div>

                <!-- Social Icon -->
                <div class="social_links_wrapper">
                    <div class="social_links">
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="#"><i class="fa fa-google"></i></a></li>
                            <li><a href="#"><i class="fa fa-youtube"></i></a></li>

                        </ul>
                    </div>

                    <!-- /.Social Button -->
                    <div class="header_login">

                        <a href="http://bim.odoobim.com">
                            <div class="blob-btn">
                                Demo
                                <span class="blob-btn__inner">
									   <span class="blob-btn__blobs">
									   <span class="blob-btn__blob"></span>
                                <span class="blob-btn__blob"></span>
                                <span class="blob-btn__blob"></span>
                                <span class="blob-btn__blob"></span>
                                </span>
                                </span>
                            </div>
                        </a>

                    </div>
                </div>

            </div>
        </div>

        <!--bottom header wrappper start-->
        <div class="transparent-menu header-area hidden-menu-bar stick">

            <div class="container">
                <div class="row">
                    <div class="bt_main_menu_wrapper">
                        <div class="main-menu-wrapper clear-fix">

                            <div class="logo float-left">
                                <a href="{% url 'webodoobim:contact' %}"><img style="width:120px;" src="{% static 'img/logo-odoo-bim-w.png' %}" alt="LOGO"></a>
                            </div>

                            <div class="serach-header bt_search_wrapper_respnsive hidden-lg hidden-md">
                                <button class="searchd"><i class="fa fa-search"></i></button>
                                <div class="searchbox">
                                    <button class="close">×</button>
                                    <form>
                                        <input type="search" placeholder="Search …">
                                        <button type="submit"><i class="fa fa-search"></i></button>
                                    </form>
                                </div>
                            </div>

                        </div>
                        <div class="sc_navigation hidden-sm hidden-xs">
                            <nav id="primary-nav" class="dropdown nav_left_margin">
                                <ul class="dropdown menu cart_dropdown_wrapper">
                                    <li><a href="{% url 'webodoobim:index' %}" title="">Inicio</a>
                                    </li>
                                    <li><a href="{% url 'webodoobim:about' %}" title="">Acerca De</a>
                                    </li>
                                    <li><a href="{% url 'webodoobim:services' %}" title="">Servicios</a>
                                    </li>
                                    <li><a href="project.html" title="">Videos</a></li>
                                    <li><a href="project.html" title="">Presentación</a></li>
                                    <li><a href="{% url 'webodoobim:blog' %}" title="">Blog</a>
                                    <li><a href="{% url 'webodoobim:contact' %}" title="">Contacto</a>
                                    </li>


                                </ul>
                            </nav>
                            <!-- Menu -->
                            <!--search -->
                            <div class="serach-header">
                                <button class="searchd"><i class="fa fa-search"></i></button>
                                <div class="searchbox">
                                    <button class="close">×</button>
                                    <form>
                                        <input type="search" placeholder="Search …">
                                        <button type="submit"><i class="fa fa-search"></i></button>
                                    </form>
                                </div>
                            </div>
                            <!-- cart code -->

                        </div>
                        <!-- /.main-menu-wrapper -->
                        <!-- mobile menu area start -->
                        <div class="mobile-menu-area visible-sm visible-xs">
                            <div class="container">
                                <div class="row">

                                    <div class="col-xs-12 cc_menu_top_margin">
                                        <!-- mobile menu start -->
                                        <div class="mobile-menu">
                                            <nav>
                                                <ul class="nav">
                                                    <li><a href="index.html">Home</a>
                                                    </li>
                                                    <li><a href="about_us.html">about us</a>
                                                    </li>
                                                    <li><a href="services.html">services</a>
                                                    </li>
                                                    <li><a href="#">pages</a>
													 <ul>
														<li><a href="about_us.html" title=""> about us</a></li>
														<li><a href="error.html" title=""> 404 error</a></li>
														<li><a href="project.html" title=""> project</a></li>
														<li><a href="services.html" title=""> services</a></li>
														<li><a href="project_single.html" title=""> project single</a></li>

													</ul>
                                                    </li>
													<li><a href="project.html" title="">project</a>
														<ul>
															<li><a href="project.html" title=""> project</a></li>
															<li><a href="project_single.html" title=""> project single</a></li>
														</ul>
													</li>
													 <li><a href="blog_single.html" title="">blog</a>
														<ul>
															<li><a href="blog_single.html" title="">blog single</a></li>
															<li><a href="blog_category.html" title=""> blog category</a></li>
														</ul>
													</li>
                                                    <li><a href="contact_us.html"> contact us</a>
                                                    </li>

                                                </ul>
                                            </nav>
                                        </div>
                                        <!-- mobile menu end -->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- mobile menu area end -->
                    </div>
                    <!-- /.main-menu-wrapper -->
                </div>
            </div>
        </div>

        <!--header section end-->
    </header>